### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by watertosea** [Huawei-Hadoop/hindex#41]
when I insert testData,there is an error.

org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 5000 actions: NotServingRegionException: 5000 times, servers with issues: xxxxx:60020, 
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatchCallback(HConnectionManager.java:1677)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.processBatch(HConnectionManager.java:1453)
        at org.apache.hadoop.hbase.client.HTable.batch(HTable.java:738)

**Comment by hy2014** [comment]
hi, how you resolve this problem?

**Comment by watertosea** [comment]
tune zk timeout to larger

**Comment by hy2014** [comment]
I also get this issue in the client, but I am not sure the problem is the same. In my env, region server log display: region is blocked when split or compact. So i want to know your detail log in the regionserver?

**Comment by watertosea** [comment]
can you send you detail log?

------------------ 原始邮件 ------------------
发件人: "hy2014"; 
发送时间: 2014年4月9日(星期三) 上午8:59
收件人: "Huawei-Hadoop/hindex"; 
抄送: "smartzjp"; 
主题: Re: [hindex] is this a bug? (#41)

I also get this issue in the client, but I am not sure the problem is the same. In my env, region server log display: region is blocked when split or compact. So i want to know your detail log in the regionserver?

**Comment by hy2014** [comment]
## Below is the region server log:

org.apache.hadoop.hbase.NotServingRegionException: event_log_pref_2_idx,b800094060ab267603d3e50f688fb17a，1395970050091.eef7ee4a2e35b400697d4ddb967df774. is closing
    at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:5819)
    at org.apache.hadoop.hbase.regionserver.HRegion.internalObtainRowLock(HRegion.java:3424)
    at org.apache.hadoop.hbase.regionserver.HRegion.getLock(HRegion.java:3519)
    at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2289)
    at org.apache.hadoop.hbase.regionserver.HRegion.batchMutateForIndex(HRegion.java:2158)
    at org.apache.hadoop.hbase.index.coprocessor.regionserver.IndexRegionObserver.postBatchMutate(IndexRegionObserver.java:398)
    at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.postBatchMutate(RegionCoprocessorHost.java:1612)
    at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2485)
    at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2117)
    at org.apache.hadoop.hbase.regionserver.HRegionServer.multi(HRegionServer.java:3809)
    at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Server.call(WritableRpcEngine.java:320)
    at org.apache.hadoop.hbase.ipc.HBaseServer$Handler.run(HBaseServer.java:1426)

**Comment by hy2014** [comment]
can you send me the detail log?
